BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Bruker" (
	"BrukerID"	INT,
	"Navn"	VARCHAR(255) NOT NULL,
	"Tlf"	VARCHAR(8) NOT NULL,
	"Adresse"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("BrukerID")
);
CREATE TABLE IF NOT EXISTS "Sal" (
	"SalNavn"	VARCHAR(50),
	"Kapasitet"	INT,
	PRIMARY KEY("SalNavn")
);
CREATE TABLE IF NOT EXISTS "Gruppe" (
	"GruppeID"	INT,
	"GruppeNavn"	VARCHAR(100) NOT NULL,
	"Betingelser"	VARCHAR(255),
	PRIMARY KEY("GruppeID")
);
CREATE TABLE IF NOT EXISTS "Rolle" (
	"RolleID"	INT,
	"RolleNavn"	VARCHAR(100) NOT NULL,
	PRIMARY KEY("RolleID")
);
CREATE TABLE IF NOT EXISTS "Skuespiller" (
	"AnsattID"	INT,
	"Navn"	VARCHAR(255) NOT NULL,
	"Tlf"	VARCHAR(8),
	"ePost"	VARCHAR(320),
	"AnsattStatus"	VARCHAR(50),
	PRIMARY KEY("AnsattID")
);
CREATE TABLE IF NOT EXISTS "AnnenAnsatt" (
	"AnsattID"	INT,
	"Navn"	VARCHAR(255),
	"Tlf"	VARCHAR(8),
	"ePost"	VARCHAR(320),
	"AnsattStatus"	VARCHAR(50),
	PRIMARY KEY("AnsattID")
);
CREATE TABLE IF NOT EXISTS "BillettKjop" (
	"KjopRef"	INT,
	"Dato"	VARCHAR(10) NOT NULL,
	"Klokkeslett"	VARCHAR(5) NOT NULL,
	"BrukerID"	INT,
	FOREIGN KEY("BrukerID") REFERENCES "Bruker"("BrukerID") ON UPDATE CASCADE ON DELETE SET NULL,
	PRIMARY KEY("KjopRef")
);
CREATE TABLE IF NOT EXISTS "Stykke" (
	"StykkeTittel"	VARCHAR(255) NOT NULL,
	"Forfatter"	VARCHAR(255),
	"SalNavn"	VARCHAR(50) NOT NULL,
	PRIMARY KEY("StykkeTittel"),
	FOREIGN KEY("SalNavn") REFERENCES "Sal"("SalNavn") ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Visning" (
	"VisningsID"	INT NOT NULL,
	"Dato"	VARCHAR(10),
	"Klokkeslett"	VARCHAR(5),
	"StykkeTittel"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("VisningsID"),
	FOREIGN KEY("StykkeTittel") REFERENCES "Stykke"("StykkeTittel") ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Sete" (
	"SeteID"	INT NOT NULL,
	"SeteNr"	INT,
	"RadNr"	INT,
	"Omerade"	VARCHAR(50),
	"SalNavn"	VARCHAR(50) NOT NULL,
	PRIMARY KEY("SeteID"),
	FOREIGN KEY("SalNavn") REFERENCES "Sal"("SalNavn") ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Billett" (
	"BillettID"	INT NOT NULL,
	"BillettPris"	DECIMAL(10, 2),
	"KjopRef"	INT NOT NULL,
	"VisningsID"	INT NOT NULL,
	"SeteID"	INT,
	"GruppeID"	INT,
	PRIMARY KEY("BillettID"),
	FOREIGN KEY("KjopRef") REFERENCES "BillettKjop"("BillettRef") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("VisningsID") REFERENCES "Visning"("VisningsID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("GruppeID") REFERENCES "Gruppe"("GruppeID") ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY("SeteID") REFERENCES "Sete"("SeteID") ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "Pris" (
	"GruppeID"	INT NOT NULL,
	"StykkeTittel"	VARCHAR(255) NOT NULL,
	"Pris"	DECIMAL(10, 2),
	
	PRIMARY KEY("GruppeID","StykkeTittel"),
	FOREIGN KEY("GruppeID") REFERENCES "Gruppe"("GruppeID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("StykkeTittel") REFERENCES "Stykke"("StykkeTittel") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Akt" (
	"AktNr"	INT NOT NULL,
	"AktNavn"	VARCHAR(255),
	"StykkeTittel"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("AktNr","StykkeTittel"),
	FOREIGN KEY("StykkeTittel") REFERENCES "Stykke"("StykkeTittel") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "JobberPa" (
	"AnsattID"	INT NOT NULL,
	"StykkeTittel"	VARCHAR(255),
	"Ansvar"	VARCHAR(255),
	PRIMARY KEY("AnsattID","StykkeTittel"),
	FOREIGN KEY("StykkeTittel") REFERENCES "Stykke"("StykkeTittel") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("AnsattID") REFERENCES "Skuespiller"("AnsattID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Spiller" (
	"AnsattID"	INT NOT NULL,
	"RolleID"	INT NOT NULL,
	PRIMARY KEY("AnsattID","RolleID"),
	FOREIGN KEY("AnsattID") REFERENCES "Skuespiller"("AnsattID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("RolleID") REFERENCES "Rolle"("RolleID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "RolleTilAkt" (
	"RolleID"	INT NOT NULL,
	"AktNr"	INT NOT NULL,
	PRIMARY KEY("RolleID","AktNr"),
	FOREIGN KEY("RolleID") REFERENCES "Rolle"("RolleID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("AktNr") REFERENCES "Akt"("AktNr") ON UPDATE CASCADE ON DELETE CASCADE
);
COMMIT;
